server:
  port: ${SERVER_PORT:80}

otel:
  sdk:
    disabled: true

popp:
  poppIssuerUrl: "http://popp-token-generator"
  sec:
    store:
      path: popp-token-Server-nist-komp61.p12
      pass: "gematik"
    key:
      alias: popp-token-Server-nist-komp61
      pass: "gematik"
